plugins {
    id 'com.android.application'
}

android {
    namespace 'com.github.benhawks.canonprint.bridge'
    compileSdk 34

    defaultConfig {
        applicationId 'com.github.benhawks.canonprint.bridge'
        minSdk 23
        targetSdk 34
        versionCode 1
        versionName '0.1.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    lint {
        abortOnError true
        checkReleaseBuilds false
        disable 'GradleDependency', 'SetTextI18n', 'HardcodedText', 'MissingApplicationIcon'
    }

    applicationVariants.all { variant ->
        variant.outputs.all {
            outputFileName = "CanonPrintBridge-${variant.name}-${variant.versionName}.apk"
        }
    }
}
